### ISSUE TITLE
[enhancement] Add missing bower.json.

### ISSUE THREAD

**Issue by timgluz** [typekit/webfontloader#174]
#### Hey, maintainer(s) of typekit/webfontloader!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, _224_ of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `typekit/webfontloader` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "typekit/webfontloader",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

**Comment by zanona** [comment]
Would be nice to reconsider bower publish

**Comment by bramstein** [comment]
The Web Font Loader is available on NPM, so you don't need bower.

**Comment by zanona** [comment]
I thought npm was dedicated to node modules only?
Wouldn't this decision make things difficult for users maintaining their web packages through bower?
A case example:

User having
- `/package.json` defining test/build and deployment dependencies in order to generate output directory. 
- `/bower.json` defining web app dependencies which will be installed into `src/vendor` directory

### Structure:
```
.
├── bower.json
├── package.json
├── node_modules
└── src
    └── vendor
```

Wouldn't this mean that if I also need node-only packages available at `node_modules` and not under `src/vendor` I then wouldn't be able to install webfontloader throught npm in this case since it would be installed under `node_modules` and not `src/vendor` as with other browser related packages?

**Comment by troygrosfield** [comment]
+1 for having bower install option.  It's dead simple to add the config and gives developers the ability to leverage whatever package installer they already have setup with their dev ecosystem.  What's the reason to not use bower?

**Comment by lexbi** [comment]
@bramstein I would also appreciate this on bower, I use bower for frontend resources, and, npm for gulp things. 

I did once try just using NPM instead of bower, but, I found it very unhelpful. When using NPM only, you can't do any sort of logic in the package.json because it's json.

I do hope you change your mind,

Many thanks
