### ISSUE TITLE
FontAwesome declared inactive on iOS Chrome & Safari

### ISSUE THREAD

**Issue by crstauf** [typekit/webfontloader#265]
I have a significant issue, that I cannot make sense of: on both Chrome and Safari on iOS, the WFL tries to load FA twice (once from internal and on inactive from CDN), and finds it to be inactive both times. In my tests, the code works perfectly on desktop. Google Fonts load fine on mobile, and are correctly reflected in the HTML class tag...

Remember, issue is on iOS Chrome and Safari; emulating in Chrome does not reveal issue.

I do not think it to be an FA issue, as linking to the stylesheet directly works just fine, as proven on the live site (not using WFL), http://spiderwebshade.com. Though, I could be wrong:

![screen shot 2015-08-06 at 5 05 44 pm](https://cloud.githubusercontent.com/assets/4573033/9123450/a801b19c-3c5d-11e5-89e0-74bbd5a918ae.png)

__CodePens__
- with issue (Google Fonts and FA loaded via WFL): http://codepen.io/crstauf/pen/rVPoLb
- without issue (Google Fonts loaded via WFL, FA by `<link>`): http://codepen.io/crstauf/pen/zGeeoo

Please remember, issue is with iOS Chrome and Safari.

Any thoughts? Have I missed a known issue with iOS or WFL or FA?

Any help at all, please.

**Comment by crstauf** [comment]
if there's nothing obvious from anyone quickly, I'll work on creating a CodePen, to further isolate and/or determine the issue.

**Comment by bramstein** [comment]
Does it work on desktop Safari? Chrome and Safari on iOS are the same rendering engine. Also, could you check those unexpected CSS token warnings? That looks suspicious.

**Comment by crstauf** [comment]
Yes, FA is loaded and active by WFL on Safari desktop. The unexpected tokens are from `filter` styles, like this one:

`filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#80ffffff', endColorstr='#ffffff', GradientType=0);`

That doesn't seem invalid; even the css file for Bootstrap has an "unexpected token."

**Comment by bramstein** [comment]
So if I understand you correctly, the fonts load and render on iOS, but the WFL does not fire the font active event?

**Comment by crstauf** [comment]
I see the second file written when I inspect, but since I've the icons set
to `display: none` until the active class is added to the `<html>` tag...
testing on the CodePen though will give proof though.

On Sunday, August 9, 2015, Bram Stein <notifications@github.com> wrote:

> So if I understand you correctly, the fonts load and render on iOS, but
> the WFL does not fire the font active event?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typekit/webfontloader/issues/265#issuecomment-129139445>
> .
>


-- 


Caleb Stauffer

**Comment by crstauf** [comment]
any movement on this? seems to be a significant issue.

**Comment by crstauf** [comment]
cannot believe this issue is being discarded; how is this not being dealt with? if I've missed something, that's fine, just say so... it seems more like a bug though. please, attention to this issue and fix asap.

**Comment by crstauf** [comment]
@bramstein any progress on fixing this? how can i help?

**Comment by rrphotosoft** [comment]
Same thing happens using "weather-icons" - these are based on font-awesome. On Google chrome 32.0 desktop. The font loads and renders fine, but the final state in the html class is -> inactive. Really look forward to any help on this issue.

**Comment by crstauf** [comment]
@bramstein is this project no longer in development and/or being supported? the newest issues on this project receiving no responses makes me wonder if this project is being replaced...? please confirm!

**Comment by kennethormandy** [comment]
I’m sure that wasn’t meant to be accusatory, @crstauf, but just because it’s something I see happening on this issue way too frequently.

@bramstein is really on top of this project to the best of his ability, and it makes me sad to see people questioning that instead of being thankful of how good he is at this. He can’t get to every issue immediately, and the project’s priorities won’t always align with the people who open issues, but that doesn’t mean it’s cool to ask him to fix this asap or question the stability of the project.

Bram has put an absolutely _massive_ amounts of work into this, and other web typography projects. My understanding is that he might get a small amount of work time to work on this project when it’s relevant to Typekit, but beyond that everything has been on his own time. Regardless, in general, he puts a lot of his own time into making sure projects like the WebFontLoader are of a certain quality.

The WebFontLoader has been very stable for a long time. [FontFaceObserver](https://github.com/bramstein/fontfaceobserver) might have more active development right now, if that is what you’re looking for, but that doesn’t necessarily mean it’s more appropriate for your project. As always, severely reduced tests cases on CodePen or JSBin or something like that always make debugging issues a lot easier. Looks like you did that, which is awesome! Maybe Bram needs new ones based on the follow-up questions he asked? Looking for other contributors who might be able to submit a PR, or digging into the issue further yourself is always helpful too.

Relative to many other open source, Bram has responded really quickly to a lot of questions on this issue tracker and we should all be super thankful he is so helpful. There was a new version of this project published six weeks ago, and issues close three weeks ago. That is really, really recently! While other projects have a huge number of contributors or even paid developers spending half their time on projects, that is not the case with this one. It’s skewed our perceptions of what is reasonable to expect from individual open source developers.

This isn’t exclusively for @crstauf, and it’s nice that you opened a pretty comprehensive issue, which is more than happens with a lot of people. This is just a general comment on some of the kind of things I see on the issue tracker here. Mostly, it’s an excuse to give props to Bram, because he does awesome work and should be getting praised in every issue.

Bram, I am super grateful for your work. You make it way better to work with type on the web, so thanks! 🍰

**Comment by crstauf** [comment]
@kennethormandy thank you for this update; that's really all I was looking for. I certainly understand priorities shift and issues cannot always be dealt with promptly... at the very least, a comment of current priorities would at least have allowed me to move forward with my performance improvements to a client's website, instead of sitting on it hoping for a fix to this issue. I am very thankful for Bram's work, and it being an incredibly stable project, expected a quickness to resolving a seemingly fatal issue. I'm not sure if that expectation is misplaced or not, but I certainly meant no disrespect to Bram or any contributor to this project... it is beyond my expertise to resolve this type of issue, though I certainly wish I was capable of helping out...

I do apologize, @bramstein, if you felt at all disrespected by my inquiries for an update on this issue and the status of the project. If there's anything I can do to help resolve this issue, please, please let me know. Would be honored to have contributed to this project in any way.

I am trying out a way of manually adding a class to the HTML tag that acts as an override class to then display Font Awesome icons, if both attempts fail. it's very hackish, but until this issue is resolved, it's what I'll have to run with, apart from not loading Font Awesome with webfontloader at all.

**Comment by crstauf** [comment]
additionally, i've updated the codepen (http://codepen.io/crstauf/pen/rVPoLb) with the latest versions of WFL and jQuery, and also removed the Google Fonts; the issue persists despite the updates and removing the Google Fonts.

**Comment by bramstein** [comment]
@kennethormandy Thanks!

@crstauf Sorry for the late response. As Kenneth pointed out, I have other responsibilities that limit the amount of time I can work on this project (unfortunately).

It took a little while, but I finally figured out what is happening here. The problem is that the two icons you passed in for the test string are exactly one em in width. Unfortunately, on iOS 6, 7, and 8 (iOS 9 appears unaffected) the default fallback glyph for characters in the private use area (which FontAwesome uses) are also exactly one em wide. This is the reason the font load detection fails --- it doesn't detect any change in width from the web font compared to the fallback font. The solution is simple: use a FontAwesome icon for the test string that is not exactly one em wide. I've had good results with `\uf240`.

**Comment by crstauf** [comment]
Wow, quite a sly little issue that turned out to be. Thanks for the info!
Never crossed my mind to try a different test string.

I appreciate your work and help on this, Bram, and will be checking out
your other projects! :-)

On Tuesday, September 22, 2015, Bram Stein <notifications@github.com> wrote:

> @kennethormandy <https://github.com/kennethormandy> Thanks!
>
> @crstauf <https://github.com/crstauf> Sorry for the late response. As
> Kenneth pointed out, I have other responsibilities that limit the amount of
> time I can work on this project (unfortunately).
>
> It took a little while, but I finally figured out what is happening here.
> The problem is that the two icons you passed in for the test string are
> exactly one em in width. Unfortunately, on iOS 6, 7, and 8 (iOS 9 appears
> unaffected) the default fallback glyph for characters in the private use
> area (which FontAwesome uses) are also exactly one em wide. This is the
> reason the font load detection fails --- it doesn't detect any change in
> width from the web font compared to the fallback font. The solution is
> simple: use a FontAwesome icon for the test string that is not exactly one
> em wide. I've had good results with \uf240.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typekit/webfontloader/issues/265#issuecomment-142313334>
> .
>


-- 


Caleb Stauffer
